FROM kong:3.9

USER root

RUN mkdir -p /usr/local/share/lua/5.1/kong/plugins/jwt_validator
COPY kong-plugins/jwt_validator/ /usr/local/share/lua/5.1/kong/plugins/jwt_validator/

ENV KONG_PLUGINS=bundled,jwt_validator

USER kong
