version: '3.9'

x-kong-config:
  &kong-env
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: kong-db
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kongpass

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  kong-net:
    external: false

services:
  kong-migrations:
    image: kong:3.9
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      <<: *kong-env
    networks:
      - kong-net
    restart: on-failure

  kong:
    # image: kong:3.9
    build:
      context: .
      dockerfile: Dockerfile.kong
    user: kong
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: /var/run/kong
      KONG_SSL_CERT: /etc/kong/ssl-cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/ssl-key.pem
    networks:
      - kong-net
    ports:
      - "9000:8000"
      - "9443:8443"
      - "9001:8001"
      - "9444:8444"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    volumes:
      - kong_prefix_vol:/var/run/kong
      - kong_tmp_vol:/tmp
      - ./kong/ssl/cert.pem:/etc/kong/ssl-cert.pem:ro
      - ./kong/ssl/key.pem:/etc/kong/ssl-key.pem:ro
    security_opt:
      - no-new-privileges

  kong-db:
    image: postgres:16
    container_name: kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data
  
  # konga:
  #   image: pantsel/konga
  #   container_name: konga
  #   ports:
  #     - "1337:1337"
  #   environment:
  #     NODE_ENV: production
  #   networks:
  #     - kong-net
  #   depends_on:
  #     - kong
